apiVersion: v1
kind: Service
metadata:
  name: radar-service
  labels:
    app: radar-app
spec:
  type: NodePort
  selector:
    app: radar-app
  ports:
    - name: http
      port: 5000        # הפורט הלוגי בתוך הקלאסטר
      targetPort: 5000  # הפורט בתוך הקונטיינר (Flask)
      nodePort: 30007   # הפורט במכונה המקומית (לגישה ישירה)
